gems:
  - jekyll-archives
  - jekyll-paginate-v2

pagination:
  enabled: true
  title: ':title - page :num'
  limit: 0
  trail:
    before: 2
    after: 2

categories:
  - Travel
  - Lifestyle
  - Featured

jekyll-archives:
  enabled: true
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
